parameters:
#    parameter_name: value

services:
    app.ldap_read_client:
        class: AppBundle\Ldap\LdapClient
        arguments: ["%ldap_read_host%", "%ldap_read_port%", "%ldap_read_dn%", "%ldap_read_pass%"]
        private: true

    app.ldap_write_client:
        class: AppBundle\Ldap\LdapClient
        arguments: ["%ldap_write_host%", "%ldap_write_port%", "%ldap_write_dn%", "%ldap_write_pass%"]
        private: true

    app.ldap_fallback_clients:
        class: AppBundle\Ldap\LdapClients
        private: true

    app.ldap_normalizer:
        class: AppBundle\Ldap\Normalizer
        arguments: ["%ldap.mapping%"]
        private: true

    app.grouphub_ldap_client:
        class: AppBundle\Ldap\GrouphubClient
        arguments: ["@app.ldap_read_client", "@app.ldap_write_client", "@app.ldap_fallback_clients", "@app.ldap_normalizer", "%users_dn%", "%groups_dn%", "%grouphub_dn%", "%formal_dn%", "%adhoc_dn%", "%admin_groups_dn%", "%user_query%", "%group_query%"]
        private: true

    app.api_normalizer:
        class: AppBundle\Api\Normalizer
        private: true

    app.api_client:
        class: AppBundle\Api\ApiClient
        arguments: ["@guzzle.client.api_grouphub", "@app.api_normalizer"]
        private: true

    app.queue:
        class: AppBundle\Service\QueueService
        arguments: ["@doctrine_cache.providers.cache"]
        private: true

    app.sync:
        class: AppBundle\Service\SyncService
        arguments: ["@app.grouphub_ldap_client", "@app.api_client", "@logger", "@app.queue", "%admin_groups_sync%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.group_manager:
        class: AppBundle\Manager\GroupManager
        arguments: ["@app.api_client", "@app.queue"]

    app.membership_manager:
        class: AppBundle\Manager\MembershipManager
        arguments: ["@app.api_client", "@app.queue"]

    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@app.api_client"]

    app.notification_manager:
        class: AppBundle\Manager\NotificationManager
        arguments: ["@app.api_client"]

    app.admin_voter:
        class: AppBundle\Security\AdminVoter
        arguments: ["@app.group_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.group_voter:
        class: AppBundle\Security\GroupVoter
        arguments: ["@app.membership_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.membership_voter:
        class: AppBundle\Security\MembershipVoter
        arguments: ["@app.membership_manager"]
        tags:
            - { name: security.voter }
        public: false

    app.form.group:
        class: AppBundle\Form\GroupType
        arguments: ['@security.authorization_checker', '@app.group_manager', '@security.token_storage']
        tags:
            - { name: form.type }

    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ['@app.api_client']

    app.exporter:
        class: AppBundle\Manager\Exporter
        arguments: ['@app.membership_manager']
