parameters:
#    parameter_name: value

services:
    app.ldap_client:
        class: AppBundle\Ldap\LdapClient
        arguments: ["%ldap_host%", "%ldap_port%", "%ldap_dn%", "%ldap_pass%"]

    app.api_client:
        class: AppBundle\Api\ApiClient
        arguments: ["@guzzle.client.api_grouphub"]

    app.sync:
        class: AppBundle\Service\SyncService
        arguments: ["@app.ldap_client", "@app.api_client", "@logger"]
